---
name: Website Request
title: "[Website Request] <Website Name>"
description: Suggest support for a new website in MALSync
labels: ["New Website"]
body:
  - type: markdown
    id: notice
    attributes:
      value: |
        **PLEASE READ THIS**

        I acknowledge that:

        - I have checked that the website is not already supported: https://github.com/MALSync/MALSync/blob/master/pages.md
          - If supported but it is not working, then please open an bug issue: https://github.com/MALSync/MALSync/issues/new/choose
        - I have searched the existing GitHub issues and this website does **NOT** have an open request
        - I will fill out the title and the information in this template
        - Support won't be added for pages that:
          - Are clones of another page
        - If you are the owner of the website, then please contact us directly on discord.
  - type: input
    id: website-name
    attributes:
      label: Website name
      description: What is the name of the website?
    validations:
      required: true
  - type: input
    id: website-link
    attributes:
      label: Website link
      description: What is the URL for the website?
    validations:
      required: true
  - type: input
    id: website-language
    attributes:
      label: Website language(s)
      description: What language(s) does the website use?
    validations:
      required: true
  - type: textarea
    id: other-details
    attributes:
      label: Other details
      description: Pleaee enter any other details for this website
    validations:
      required: false
